sonar.projectKey=home-essentials-market
sonar.organization=your-org-name

# Tell SonarCloud where to look for your code
sonar.sources=backend,frontend
sonar.python.version=3
sonar.exclusions=**/venv/**, **/node_modules/**
